### ISSUE TITLE
The compiling problem

### ISSUE THREAD

**Issue by somebody27** [mROS-base/mros2-asp3-f767zi#49] opened 2021-12-19 15:09 UTC
I followed the steps to run the code, but it didn't work well as follows:
![image](https://user-images.githubusercontent.com/46376373/146679960-978fbdae-4aa8-45b0-a04e-5b549c49ab36.png)
This is the first time I use mros2 and Toppers, hope to get some help

**Comment by takasehideki** [comment] 2021-12-20 08:48
@somebody27 thank you so much for trying our repository!!
Could you send the whole log of running `make app=echoreply_uint16`? 
We cannot immediately find out the cause of this error message, but we may be able to get hints from other part of log messages.

**Comment by takasehideki** [comment] 2021-12-20 08:50
And one more question, is this message printed in othe app builds? (e.g., `make app=echoreply_string`)

**Comment by somebody27** [comment] 2021-12-20 13:04
Yes, all the other app builds have the same error.

**Comment by somebody27** [comment] 2021-12-20 13:06
[make.log](https://github.com/mROS-base/mros2-asp3-f767zi/files/7745455/make.log)
This is the corresponding  log file

**Comment by somebody27** [comment] 2021-12-20 13:31
I think that's because of the undefined functions CRE_CYC...as I don't know where it is defined.

**Comment by takasehideki** [comment] 2021-12-21 01:12
@somebody27 thanks for sharing the build log.
I doubt the issue is with the version of ruby. Here is the version in my environment.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
```

Which is the version do you use?

**Comment by takasehideki** [comment] 2021-12-21 01:16
NOTE: `CRE_CYC` is the API that statically generate the cyclic handler in TOPPERS/ASP3 kernel (like `xTimerCreate` in FreeRTOS).
TOPPERS has a policy of statically generating kernel resources, such as tasks, cyclic handlers, semaphoe, and so on. These are defined in the .cfg file with uppercase APIs and are generated by the configurator written in Ruby at the build step.

**Comment by somebody27** [comment] 2021-12-21 05:24
@takasehideki Hello, thank you for your advice. 

- I checked and I have the same ubuntu and ruby version with you, but my arm-none-eabi-gcc version are higher, then I changed gcc version to 7.3.1. It works~~
- I noticed the gcc version at first because I read your "Envorinmental setup" part, but I thought it wouldn't affect the compiling, so I ignored it.
- Thank you again

**Comment by takasehideki** [comment] 2021-12-21 08:08
@somebody27 Thanks again! I'm happy you can now enjoy mros2 world! Please feel free to let us know if you have any issues or requests in the future.

We understand that it is desirable to work with the default gcc version that can be installed with apt on Ubuntu. It was different from your log, but I have confirmed that this repo cannot be built in this environment. So I created a new issue #50, and decided to close this issue.

**Closed by takasehideki** 2021-12-21 08:08 UTC
